version: "3"

services:
  monitoring:
    image: tianon/true
  postgres:
    container_name: monitoring_postgres
    image: postgres:10
    ports:
      - 5455:5432
    volumes:
      - ./db:/var/lib/postgresql/10/main
    env_file:
      - .env
